name: 🐛 Bug Report
description: Report a bug in the LinkedIn Post Generator system
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Discord Bot
        - HTML Web App
        - Database/PostgreSQL
        - LinkedIn API Integration
        - Configuration/Environment
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Tell us about your environment
      placeholder: |
        - OS: [e.g., macOS 14.1, Ubuntu 22.04, Windows 11]
        - Python Version: [e.g., 3.11.5]
        - Discord.py Version: [e.g., 2.3.2]
        - PostgreSQL Version: [e.g., 14.9]
        - Installation Method: [e.g., pip, docker, source]
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste any relevant log output or error messages
      render: shell
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have removed any sensitive information (tokens, passwords, etc.)
          required: true